### ISSUE TITLE
Can't get script to start

### ISSUE THREAD

**Issue by forsomefun** [beaston02/SMrecorder#8] opened 2017-10-05 17:04 UTC
I just realized that the script is not even starting on my ubunutu system
running the old command
python3 
or even python3.5 path to file.py does not work

it doesn't error out, just shows a blank screen with no logs. So it seems that no files are being generated.

**Comment by Houhie** [comment] 2017-10-09 05:15
It would appear the problem is in the while loop that starts on line 11 of SM.py. It would seem this is an infinite loop. If I find a solution I'll post back here.

**Comment by Houhie** [comment] 2017-10-09 05:31
So when I print "result" I get this error message:

`{'status': 'SM_ERROR', 'requestkey': 'b53c1069c2b5a18d56eaa4c88a2a37a8facc10c4eb365139ca158f899b295f4d', 'errors': [{'error': '404', 'message': 'Page not found, check that the requested endpoint is correct.'}], 'notifications': ['error_msg=Configured controller for route not found']}
`

This would be the problem I believe, though it's a bit beyond my expertise to try and find a solution.

I think this is something streamate changed on their end, because I was initially using an older version when I had encountered this error as well. Hopefully this helps save some time in formulating a fix.

**Comment by beaston02** [comment] 2017-10-16 23:12
Hey, Sorry for the slow reply. Life has been crazy here, and because of everything, Ive taken a break from the coding. 

I just sat down and looked into this finally. I believe I have it fixed. I have done about 10 minutes of testing, but it is starting the recording, and the file is playable on my mac, so hopefully I didnt miss anything! 

I will post the update now :)

**Comment by beaston02** [comment] 2017-10-16 23:16
I just posted the update. Im going to go ahead and close this issue. Please reopen it if this issue continues

(for what its worth, the issue was a change in the api used to get the online models. The URL changed, and it requires cookies to get additional pages. Also, it seems to only return 24 models regardless of the number set in the URL data, where before I had it grabbing 500 per request, so the check may take a little longer, but shouldnt be bad - Ill look into this more later).

**Closed by beaston02** 2017-10-16 23:16 UTC
